version: "2.1"

volumes:
  deconz-data:

services: 

  deconz:
    image: marthoc/deconz:armhf
    network_mode: host
    restart: always
    volumes:
      - "deconz-data:/root/.local/share/dresden-elektronik/deCONZ"
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - TZ=Europe/Oslo
